### ISSUE TITLE
ReviewImage 관련 : 특히 디자인/프론트엔드 꼭꼭 봐주세요

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#15]
생각해보니 이것도 난관이네요.
현재 Django ORM상 ReviewImage의 review ForeignKey가 PenReview가 아니라 Review를 가리키고 있는데, 이게 정상적으로 PenReview를 가리키고 있어도 제대로 기능할까요..?
지금 생각나는 방법은 ReviewImage 모델을 포기하고  https://github.com/pcjs156/LionStore/blob/b06a3bbcadcadacd8a7a4acfdc4b8b4caa2a5475/account/models.py#L72L74(account.models.Customer)에서 관심 있는 펜 종류를 1~3순위까지 미리 정의해놓고 기본값을 주는 방법과 마찬가지로 리뷰에 업로드 할 수 있는 최대 사진 수를 정해놓고 기본값을 주는 방법입니다. **혹시 이것보다 더 좋은 방법을 알고 계시면 코멘트 달아주시고, 만약 이렇게 구현한다면 리뷰당 최대 사진 갯수는 몇 장까지 허용하는게 좋을지 적어주세요.**

**Comment by pcjs156** [comment]
모델을 자꾸 바꾸네요 미안해요 ㅠㅠ

**Comment by pcjs156** [comment]
또 음,, 송구스럽습니다만 ㅠ 아직 한 페이지에서 두 가지 Form을 처리하는 방법을 몰라서 Review 모델 Create 할 때 페이지를 나눠서(...) Review 모델에 정의된 요소들을 처리하고, 이어지는 페이지에서 리뷰 이미지를 업로드해야될지도 모르겠네요. 공부해보겠습니다아ㅏㅇㄱ

**Comment by pcjs156** [comment]
++++) 아니면 그냥 속편하게 ReviewImage를 PenReviewImage로 바꾸고 해당 모델이 Review가 아니라 PenReview를 바라보는 1:N 관계로 수정하는 방법도 있겠네요! 이건 이거 나름대로 한 페이지에서 여러 이미지를 업로드 하는 방법을 공부해봐야 될 것 같기는 합니다만 ㅠ
또 이런 방법으로 구현하게 되면 웹 페이지에 어떻게 그걸 보여줄건지도 다시 고민해봐야겠네요. 업로드 가능한 최대 이미지 수를 제한할 수 없으면,,, 악

**Comment by pcjs156** [comment]
아무도 답변을 안 주시네요 ㅠㅠ
https://chohyeonkeun.github.io/2019/07/06/190706-django-multi-image-upload/ 참고해서 도전해보겠습니다

**Comment by hyeonsoo3413** [comment]
늦게 답변드려 죄송합니다ㅜㅜ   리뷰이미지 3장이면 충분하다고 생각합니다!

**Comment by pcjs156** [comment]
우선 한 번에 여러장을 올리는 방법을 찾아 보기는 해야겠는데, 디자인 할 때 사진이 너무 많아져도 혹시 문제가 있지 않을까요? 혹시 CSS나 JS로 해결 가능하신가요..? @youngjin2639 @hyeonsoo3413

**Comment by youngjin2639** [comment]
리뷰이미지의 수는 저도 정해져있는게 좋은 것 같아요 !! 3-4 장 정도면 좋을 것 같습니다

**Comment by youngjin2639** [comment]
> 우선 한 번에 여러장을 올리는 방법을 찾아 보기는 해야겠는데, 디자인 할 때 사진이 너무 많아져도 혹시 문제가 있지 않을까요? 혹시 CSS나 JS로 해결 가능하신가요..? @youngjin2639 @hyeonsoo3413 

음 일반적으로 상품리뷰할때 사진이 최소 3장정도는 필요하니 .. 최소 3장 최대 6장정도로 하고 어짜피 엄청나게 많은 리뷰를 만들어 놓을 것은 아니니 괜찮지 않을까요.?.

**Comment by pcjs156** [comment]
@youngjin2639 이게 음,, 지금 알고 있는 방법으론 Customer 모델에서 펜 1~3순위 정하듯 고정적인 수로 이미지를 받는 방법밖에 생각이 안나는데 한 번에 여러 장 이미지를 올리고 이미지 수를 제한할 수 있는 방법을 찾아 봐야 겠네요

**Comment by pcjs156** [comment]
@youngjin2639 @hyeonsoo3413 
Review 모델에 ImageField 6개를 정의하고, 이미지가 업로드 되지 않았을 경우 제품의 기본 이미지를 사용하는 걸로 하겠습니다. 복잡하겠네요 ㅠ

**Comment by pcjs156** [comment]
앗 기본이미지 지정 깜빡했네요 해놓겠습니다

**Comment by pcjs156** [comment]
https://github.com/pcjs156/LionStore/commit/dda63c419f2f568077bc6cb054026ac7e529b17b
리뷰를 등록할 때 리뷰 이미지가 등록되지 않으면 자동으로 제품의 대표 이미지를 입력받도록 해,, 두었습니다,, 만.
자동으로 제품 row를 생성하는 mainApp.tools.automativeFilling_Product를 만들던 시점엔 ProductImage라는 모델이 Product를 참조하는 관계였어서 대표 이미지까지는 기본적으로 저장되지 않도록 구현 되어 있네요. 아마 에러가 빵빵 터질 수도 있을 것 같으니 적당한 이미지를 아무거나 가져다 놓겠습니다 ㅠ

**Comment by pcjs156** [comment]
> [dda63c4](https://github.com/pcjs156/LionStore/commit/dda63c419f2f568077bc6cb054026ac7e529b17b)
> 리뷰를 등록할 때 리뷰 이미지가 등록되지 않으면 자동으로 제품의 대표 이미지를 입력받도록 해,, 두었습니다,, 만.
> 자동으로 제품 row를 생성하는 mainApp.tools.automativeFilling_Product를 만들던 시점엔 ProductImage라는 모델이 Product를 참조하는 관계였어서 대표 이미지까지는 기본적으로 저장되지 않도록 구현 되어 있네요. 아마 에러가 빵빵 터질 수도 있을 것 같으니 적당한 이미지를 아무거나 가져다 놓겠습니다 ㅠ

ㅎㅎ 포기.

**Comment by hyeonss33** [comment]
> 우선 한 번에 여러장을 올리는 방법을 찾아 보기는 해야겠는데, 디자인 할 때 사진이 너무 많아져도 혹시 문제가 있지 않을까요? 혹시 CSS나 JS로 해결 가능하신가요..? @youngjin2639 @hyeonsoo3413

어떤 문제가 생길까요?..

**Comment by pcjs156** [comment]
> > 우선 한 번에 여러장을 올리는 방법을 찾아 보기는 해야겠는데, 디자인 할 때 사진이 너무 많아져도 혹시 문제가 있지 않을까요? 혹시 CSS나 JS로 해결 가능하신가요..? @youngjin2639 @hyeonsoo3413
> 
> 어떤 문제가 생길까요?..

@hyeonss33 
그걸 웹 페이지에 보여주는 작업을 자바스크립트나 CSS로 해결해야 될 것 같은데, 일단은 제가 잘 못 합니다 ㅠ
예를 들어서 리뷰 사진이 10장이 나오면 그걸 어떻게 배치할지, 보여줄지를 해결해야 하는데 저번 아이디어톤 프로젝트에서도 그걸 못 했었어서,, ㅜㅜ
리뷰 사진은 우선 최소 1장, 최대 6장까지 등록 가능한 것 까지 알아두시면 될 것 같습니다.

**Comment by pcjs156** [comment]
헉 그 이미지 추가하기 버튼을 이런 식으로 구현하는건 어떨까요?
https://nowonbun.tistory.com/646
