### ISSUE TITLE
그리고 영원한 숙제,, 지도 연결하기

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#16]
ㅋㅋㅋㅋㅋㅋㅋ큰 틀이 잡히면 그 때부터 시작하죠,, folium이든 지도 API든 되는대로 다들 공부해보아요,,

**Comment by pcjs156** [comment]
#18 
카카오맵 API을 이용했고, 지도 위 임의의 위치를 클릭하면 마커와 함께 도로명/지번 주소가 나오는 기능을 구현했습니다.

따로 JS파일을 분리 해놓지 않아서 코드가 조금 보기 안좋은데(...) http://localhost:8000/store/newMapTest로 접근하셔서 아무 곳이나 찍은 다음 아래 submit 버튼을 누르면 콘솔창에 해당 위치의 위도/경도 값이 print함수로 출력됩니다. 여기 있는 코드를 그대로 써서 문방구 사장님 회원가입 기능, 그리고 근처 문방구 찾기 기능을 사용하기 위해 유저의 위치를 입력받는 기능 두 가지에 적용할 수 있을 것 같습니다.
카카오맵 API에서 제공하는 예시 코드(https://apis.map.kakao.com/web/sample/coord2addr/)를 조금 수정해서 썼는데, Django Form이 웹 페이지에 모델의 필드들을 input 형태로 쏴? 주는걸 참고해서 마커 위에 표시되는 도로명/지번 주소 아래에 style:"visibility:hidden; display:none" 속성을 준 input 태그를 form 태그 안에 넣은 다음 읽어 들이는 방법을 썼습니다.

여기서 문제는, 도로명/지번 주소까지는 나오는데 그 하위의 상세 주소(예를 들어 xx빌딩의 y호에 문구점이 있다고 하면)까지는 입력이 되지 않는 점입니다. 그래서 이걸 해결하려면 Customer 모델에 상세 주소를 입력받기 위한 CharField를 추가해야 되는데, 혹시 도로명/지번 주소로 충분하다고 생각되는 분 계신가요? 의견을 듣고 싶습니다.

**Comment by se0983** [comment]
저는 도로명/지번 주소까지만 나와도 충분하다고 생각합니다!!
