### ISSUE TITLE
faker 패키지 사용!!

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#19]
https://www.notion.so/4eed5a2343bb4f09874fe6c56ea4ace8?v=138c8b8b488e42b6a2cc603714db9e4f&p=fcbb8fac1ffe4f54842806da7df2bdfb
상단 노션 보시면 faker라고 해서, 랜덤하게 문자열 값 등등을 받을 수 있는? 테스트/시연하기에 꽤 편한 도구가 있어서 활용해 보려고 합니다.

명령어는 가상 환경을 켜고 다음과 같이 입력하시면 됩니다.
윈도우 : _pip install faker_
맥/리눅스 : _pip3 install faker_

**Comment by youngjin2639** [comment]
장고 인스톨하는것처럼 똑같이 하면 되죱?!

**Comment by pcjs156** [comment]
> 장고 인스톨하는것처럼 똑같이 하면 되죱?!

@youngjin2639 옙 맥os니까 아마 pip3로 하시면 될거에용
