### ISSUE TITLE
뷰 생성시 참고사항

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#40]
헷갈리지 않게 작업하려고 페이지를 직접적으로 표시하는 view는 함수 이름 뒤에 _view를 붙였고, 그렇지 않은 함수들은 _view를 붙이지 않았습니다. 작업하실 때 참고해 주세요!

ex) 제품 상세 정보를 렌더링하는 **productDetail_view**
https://github.com/pcjs156/LionStore/blob/86ec470e5d39b631c01ca61f2fc533e96f1c8405/mainApp/views.py#L74L109

ex) 제품에 표시된 좋아요를 제거하는 **productDislike**
https://github.com/pcjs156/LionStore/blob/86ec470e5d39b631c01ca61f2fc533e96f1c8405/mainApp/views.py#L134L139

**Comment by se0983** [comment]
넵
