### ISSUE TITLE
유저에 따른 Tag 유무

### ISSUE THREAD

**Issue by youngjin2639** [pcjs156/LionStore#43]
문방구 사장님이랑 웹셀러가 회원가입 진행시 , 펜 사용성향을 단어로 정리한 유저 태그 작성 칸이 뜨지 않습니다.

유저태그를 판매자한테 붙이는 것이 맞을까요 ? 유저태그의 본 의도는 유저들의 사용성향을 분석하려는 의도인데

판매자들이 유저태그를 달 수 있게 하면 자신의 주 판매품목에 대한 태그를 달 것이라 의도에 적합하지 않을 것 같아요 

어떻게 생각하시나요 !

만약 태그 유무를 전체사용자에서 분리하게되면 productDetail페이지 HTML구성이 달라지기때문에 여쭤봅니당

**Comment by pcjs156** [comment]
문구점 사장님과 웹 판매자 역시 리뷰를 작성할 수 있는 것 까지는 좋습니다만, 영진씨 말대로 유저 태그는 리뷰를 작성한 리뷰어의 성향을 다른 리뷰어가 참고할 수 있도록 하기 위한 데이터니까 지금 회원가입 폼 그대로 판매자는 태그를 입력 받지 않는 걸로 유지했으면 좋겠습니다.
다만 이 경우 BooleanField로 정의된 유저 유형에 따라 리뷰에 보여지는 데이터나 디자인이 조금씩 달라질 수도 있으니(판매자의 리뷰엔 유저 태그가 보이면 안된다던지) 페이진 디자인 맡아주신 **@hyeonsoo3413 @youngjin2639 님이 정의된 모델 참고하셔서 productDetail, reviewDetail 페이지에 유저 유형 별로 어떤 데이터가 표시되어야 하는지 코멘트로 달아 주실 수 있으신가요? 코멘트 남겨주시면 템플릿 문법으로 요구 사항 반영해 놓겠습니다.**
백엔드 @se0983 @yeahjin 맡고 계신 두 분도 위에 언급된 모델 관련해서 의견 있으시면 남겨주세요!

**Comment by se0983** [comment]
저도 판매자에게는 유저 태그를 적용하지 않는 것이 유저 태그의 본 의도에 맞다고 생각합니다.

**Comment by pcjs156** [comment]
우선 

> 문방구 사장님이랑 웹셀러가 회원가입 진행시 , 펜 사용성향을 단어로 정리한 유저 태그 작성 칸이 뜨지 않습니다.
> 
> 유저태그를 판매자한테 붙이는 것이 맞을까요 ? 유저태그의 본 의도는 유저들의 사용성향을 분석하려는 의도인데
> 
> 판매자들이 유저태그를 달 수 있게 하면 자신의 주 판매품목에 대한 태그를 달 것이라 의도에 적합하지 않을 것 같아요
> 
> 어떻게 생각하시나요 !
> 
> 만약 태그 유무를 전체사용자에서 분리하게되면 productDetail페이지 HTML구성이 달라지기때문에 여쭤봅니당

우선 유저 태그가 reviewDetail 페이지에 뜨도록 해놓았습니다.
또한, @youngjin2639 @se0983 님 의견 반영해서 해당 리뷰의 작성자가 리뷰어일 때만 유저 태그가 보이도록 템플릿 문법을 적용했습니다!

**Comment by pcjs156** [comment]
> 우선
> 
> > 문방구 사장님이랑 웹셀러가 회원가입 진행시 , 펜 사용성향을 단어로 정리한 유저 태그 작성 칸이 뜨지 않습니다.
> > 유저태그를 판매자한테 붙이는 것이 맞을까요 ? 유저태그의 본 의도는 유저들의 사용성향을 분석하려는 의도인데
> > 판매자들이 유저태그를 달 수 있게 하면 자신의 주 판매품목에 대한 태그를 달 것이라 의도에 적합하지 않을 것 같아요
> > 어떻게 생각하시나요 !
> > 만약 태그 유무를 전체사용자에서 분리하게되면 productDetail페이지 HTML구성이 달라지기때문에 여쭤봅니당
> 
> 우선 유저 태그가 reviewDetail 페이지에 뜨도록 해놓았습니다.
> 또한, @youngjin2639 @se0983 님 의견 반영해서 해당 리뷰의 작성자가 리뷰어일 때만 유저 태그가 보이도록 템플릿 문법을 적용했습니다!

확인해보시고 혹시 해당 구현 사항에 문제가 없다면 이슈 닫아주세요! @youngjin2639
