### ISSUE TITLE
html 파일에 view를 통해 템플릿 문법으로 필요한 데이터를 보내주는 작업

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#49]
https://github.com/pcjs156/LionStore/blob/52691a33cbd8d3dc8b5a2b70ba6dc97c334af830/mainApp/templates/mainPage.html#L31L33
위 코드처럼 @youngjin2639 @hyeonsoo3413 님이 디자인 작업을 하면서 웹 페이지에 표시되어야 할 데이터들을 view, 템플릿 문법을 통해 표시해주는 작업을 @se0983 님이 해주시는건 어떨까요? SellInfo 제외하면 기초적인 작업들은 대부분 끝이 난 것 같아서요!

**Comment by pcjs156** [comment]
혹시 구현하다 어려운게 있으시면 @se0983 님이 저한테 따로 연락주시거나 이슈로 남겨주세요!

**Comment by pcjs156** [comment]
이슈 #29 와 어느정도 이어지는 작업이니 여기서 #29 까지 상의하고 결정하고 작업하는걸로 하죠!

**Comment by se0983** [comment]
넵 그때 올려주신 와이어프레임 참고해서 데이터들 표시해주면 되나요?

**Comment by pcjs156** [comment]
> 넵 그때 올려주신 와이어프레임 참고해서 데이터들 표시해주면 되나요?

와이어프레임이 어느정도 구체적으로 정해졌는지 저도 잘은 모르겠네요 ㅠ 디자인 맡고 계신 분들하고 상의해가면서 작업하시면 될 것 같습니다.
