### ISSUE TITLE
관리자 페이지

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#52]
신고당한 게시물을 확인하거나, 제품 등록 요청을 확인하는 등의 기능이 필요할 것 같습니다.
기존의 admin 페이지를 커스텀 해도 좋을 것 같네요!

**Comment by youngjin2639** [comment]
신고를 한다면 그 이유에는 뭐가잇을까요..?

**Comment by pcjs156** [comment]
> 신고를 한다면 그 이유에는 뭐가잇을까요..?

판매정보는 사실과는 다른 판매정보(가격 등)이 있을 것 같고, 리뷰에는 욕설/비방 등의 사유가 있지 않을까 싶습니다.

**Comment by pcjs156** [comment]
@se0983 
신고기능이 일단,, 사라졌습니다 짜잔,,
조금 사족의 느낌이 나는 기능이니, 구현은 일단 미뤄두죠 ㅠ
