### ISSUE TITLE
마이페이지 구현

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#53]
이전에 본인이 작성한 리뷰 목록과 좋아요를 누른 리뷰/제품을 확인할 수 있는 기능이 필요합니다.

**Comment by youngjin2639** [comment]
이전에 본인이 작성한 리뷰 목록 은 볼 수 없지만 좋아요를 누른 리뷰/제품을 확인할 수 있는 기능 은 하는걸로 알고있었는데 ..!! 배포된 페이지에 보니까 마이페이지 탭이아예 없네요 ㅇㅂㅇ

**Comment by pcjs156** [comment]
> 이전에 본인이 작성한 리뷰 목록 은 볼 수 없지만 좋아요를 누른 리뷰/제품을 확인할 수 있는 기능 은 하는걸로 알고있었는데 ..!! 배포된 페이지에 보니까 마이페이지 탭이아예 없네요 ㅇㅂㅇ

그렇네요! 지금 이슈 등록해놓고 작업 시작하겠습니다.
이전에 본인이 등록한 리뷰를 볼 수 있어도 좋지 않을까요?

**Comment by pcjs156** [comment]
@youngjin2639 @hyeonsoo3413 
마이 페이지 같은 경우에는 웹 페이지 구조가 다양하게 나올 수 있을 것 같은데, 한 페이지에 좋아요를 누른 리뷰 목록, 좋아요를 누른 제품 목록, (찬성하신다면) 본인이 이전에 작성한 리뷰 목록 세 가지를 동시에 보여주는게 좋을까요, 아니면 마이페이지에서 각각의 메뉴로 접근할 수 있는게 좋을까요?
또한 각각의 목록을 보여주기 위한 페이지를 만든다면, 페이지네이션을 활용하는게 좋을까요?

**Comment by youngjin2639** [comment]
> @youngjin2639 @hyeonsoo3413
> 마이 페이지 같은 경우에는 웹 페이지 구조가 다양하게 나올 수 있을 것 같은데, 한 페이지에 좋아요를 누른 리뷰 목록, 좋아요를 누른 제품 목록, (찬성하신다면) 본인이 이전에 작성한 리뷰 목록 세 가지를 동시에 보여주는게 좋을까요, 아니면 마이페이지에서 각각의 메뉴로 접근할 수 있는게 좋을까요?
> 또한 각각의 목록을 보여주기 위한 페이지를 만든다면, 페이지네이션을 활용하는게 좋을까요?

저랑 현수님의 의견은 본인이 이전에 작성한 리뷰 목록 세 가지를 한 페이지에 동시에 보여주는 것이 좋을 것 같다는 의견입니다 ! 메인페이지 구성과 비슷하게요
