### ISSUE TITLE
계정 관련 부가 기능

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#54]
가능하다면 비밀번호 찾기, 이메일 인증, SNS 계정 인증같은 부가 기능도 추가해보고 싶네요! 주기적으로 이메일로 문구를 추천해 주는 것도 좋을 것 같습니다.

**Comment by youngjin2639** [comment]
> 가능하다면 비밀번호 찾기, 이메일 인증, SNS 계정 인증같은 부가 기능도 추가해보고 싶네요! 주기적으로 이메일로 문구를 추천해 주는 것도 좋을 것 같습니다.

저도 뉴스레터 같은 거 하고싶습니당.. 근데 디자인까지 할 시간은 될지 ㅜ

**Comment by pcjs156** [comment]
> > 가능하다면 비밀번호 찾기, 이메일 인증, SNS 계정 인증같은 부가 기능도 추가해보고 싶네요! 주기적으로 이메일로 문구를 추천해 주는 것도 좋을 것 같습니다.
> 
> 저도 뉴스레터 같은 거 하고싶습니당.. 근데 디자인까지 할 시간은 될지 ㅜ

만약 한다면 html/CSS만 사용할 예정이고 보내질 내용은 지금 의논중인 pr #58 과 같은 방법으로 제품/리뷰를 선별해 자동으로 보내주는 기능까지만! 구현하게 될 것 같습니다.
