### ISSUE TITLE
펜 선호도 수정 건의

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#59]
pr #58 에서 말씀 드렸듯이, 선호 펜 종류 순위의 경우에는 유사도 계산에 사용할 값이 아닌 것 같습니다.  메인 페이지 등에서 본인이 가입 시에 선호 펜 종류 로 설정한 펜의 최신/인기 리뷰를 보여주는게 나을 것 같은데 어떻게 생각하시나요?
또한 "기타" 선택지를 "미선택" 선택지로 바꾸고, 각 선호 펜 종류 필드에 순위로 가중치를 두지 않고 로그인시 "미선택" 선택지로 저장되지 않은 선호 펜 종류 필드가 있는 경우 해당 펜 종류(카레고리)의 인기 리뷰를 보여주는 것도 좋을 것 같습니다.

**Comment by youngjin2639** [comment]
> pr #58 에서 말씀 드렸듯이, 선호 펜 종류 순위의 경우에는 유사도 계산에 사용할 값이 아닌 것 같습니다. 메인 페이지 등에서 본인이 가입 시에 선호 펜 종류 로 설정한 펜의 최신/인기 리뷰를 보여주는게 나을 것 같은데 어떻게 생각하시나요? --> 저도 그게더 나을것 같습니다 
> 또한 "기타" 선택지를 "미선택" 선택지로 바꾸고, 각 선호 펜 종류 필드에 순위로 가중치를 두지 않고 로그인시 "미선택" 선택지로 저장되지 않은 선호 펜 종류 필드가 있는 경우 해당 펜 종류(카레고리)의 인기 리뷰를 보여주는 것도 좋을 것 같습니다. --> 무슨말인지 살짝 모르겠음 . 유저가 선호 펜 필드를 미선택으로 놔두었을 경우 랜덤하게 추천해주는게 낫지않을까요 ? 총 인기순으로 추천해주던지요

**Comment by pcjs156** [comment]
> > pr #58 에서 말씀 드렸듯이, 선호 펜 종류 순위의 경우에는 유사도 계산에 사용할 값이 아닌 것 같습니다. 메인 페이지 등에서 본인이 가입 시에 선호 펜 종류 로 설정한 펜의 최신/인기 리뷰를 보여주는게 나을 것 같은데 어떻게 생각하시나요? --> 저도 그게더 나을것 같습니다
> > 또한 "기타" 선택지를 "미선택" 선택지로 바꾸고, 각 선호 펜 종류 필드에 순위로 가중치를 두지 않고 로그인시 "미선택" 선택지로 저장되지 않은 선호 펜 종류 필드가 있는 경우 해당 펜 종류(카레고리)의 인기 리뷰를 보여주는 것도 좋을 것 같습니다. --> 무슨말인지 살짝 모르겠음 . 유저가 선호 펜 필드를 미선택으로 놔두었을 경우 랜덤하게 추천해주는게 낫지않을까요 ? 총 인기순으로 추천해주던지요

템플릿 문법을 이용해서 만약 선호 펜을 등록하지 않았을 경우 임의의 카테고리의 인기 리뷰를 표시하지 않고, 선호 펜을 입력했을 경우 해당 카테고리의 인기 리뷰를 보여주는 것을 의도했습니다.
유저가 선호 펜 필드를 미선택으로 놔두었을 경우 랜덤하게 카테고리를 추천해주신다는 말씀이신가요?
