### ISSUE TITLE
검색어 입력 안했을시 뜨는 페이지

### ISSUE THREAD

**Issue by hyeonss33** [pcjs156/LionStore#63]
![캡처](https://user-images.githubusercontent.com/63245820/90982819-d4742480-e5a4-11ea-9a62-6e0a24dbd3c2.PNG)

검색어 입력이 안되는 상황에서는 팝업으로 "검색어를 입력해주세요!" 라고 뜨는 것이 더 좋을 것 같다는 의견이 있었습니다.

**Comment by se0983** [comment]
제품명 검색, 키워드 검색, 태그 검색 모두 적용해야 하나요?

**Comment by pcjs156** [comment]
> 제품명 검색, 키워드 검색, 태그 검색 모두 적용해야 하나요?

검색 메뉴는 navBar의 키워드 검색, footer의 태그 검색 두 가지밖에 없고, 두 input 태그에만 적용해 주시면 됩니다.

**Comment by se0983** [comment]
navBar의 키워드 검색, base의 태그 검색에 html input태그 속성인 required 추가했습니다.
