### ISSUE TITLE
mainApp의 ProductRequest C 구현

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/LionStore#9]
메인 페이지 상단 NavBar에서 상품(Product 모델) 등록을 요청하는 기능을 구현해야 합니다.
비교적 간단할 것 같네요!

**Comment by se0983** [comment]
이번주내로 해결해보겠습니다!

**Comment by pcjs156** [comment]
작업하실 때 해당 기능은 상단 NavBar에서 접근할 수 있도록 구현하기로 했으니 base.html의 header태그 안쪽에 해당 기능으로 이어지는 Template/View를 연결해주면 되겠네요!
하다가 막히시면 정규 세션 4주차 자료나, 멋사 라이브러리 [Django] BASIC 4, 아니면 https://wayhome25.github.io/django/2017/02/28/django-03-lotto-project-8/ 참고하셔보세용. 그래도 어려우면 저나 다른 분들한테 꼭 질문주시구요!

**Comment by pcjs156** [comment]
@se0983 
정정합니다! 디자인 팀이랑 이야기 해봤는데, CRUD 모두 구현해야 될 것 같습니다. 가능하신가요?
